from setuptools import setup


def readme():
    with open('README.md') as f:
        return f.read()


setup(
    name='markdown-toc',
    version='1.2.4',  # Reflected in __init__
    description='Autogenerated Table of Contents for Github Markdown or Bear Notes',
    long_description=readme(),
    long_description_content_type='text/markdown',
    url='https://github.com/alexander-lee/markdown-github-bear-toc',
    author='Alexander Lee',
    author_email='hello@alexanderlee.co',
    license='LICENSE',
    keywords='markdown md github bear table of contents toc',
    packages=['markdowntoc'],
    install_requires=['python-dateutil'],
    scripts=['bin/markdown-toc']
)
